version: "3.7"

services:
    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./postgres/.env
    django:
        build: 
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - django_static_volume:/usr/src/app/api/static
        expose:
            - 8000
        env_file:
            - ./api/.env
        command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
        depends_on:
        - db
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
            args:
                - API_SERVER=${ENV_API_SERVER}
        volumes:
            - react_static_volume:/usr/src/app/frontend/build/static
        expose:
            - 3000
        env_file:
            - .env
        command: serve -s build -l 3000
        depends_on:
            - django
    nginx:
        restart: always
        build: ./nginx
        volumes:
            - django_static_volume:/usr/src/app/api/static
            - react_static_volume:/usr/src/app/frontend/static
        ports:
            - 80:80
        depends_on:
            - frontend

volumes:
    postgres_data:
    django_static_volume:
    react_static_volume:
